menus:
    #------- First Menu - also accessible via /qm
    # Menu Title:
    Default Menu:
        #Menu Type
        type: Menu
        #Command to open the menu e.g. /qm menu1
        command: menu1
        # Menu Option List
        options: 
            # Option Text : Option Command
            An Option : /say Option selected
            Show me a Value Menu : /qm menu2
    #------- Second Menu
    # Menu Title:
    Default Value Menu:
        #Menu Type
        type: ValueMenu
        #Command to open the menu e.g. /qm menu2
        command: menu2
        # Question to ask after option # has been chosen
        question: How many do you want?
        # Menu Option List
        options: 
            # Option Text : Option Command
            Give me cheese : /give *user* cheese *value*
            Give me cake : /give *user* cake *value*