name: MenuMetaMod

main: com.shawlyne.mc.MenuMetaMod.MenuMetaMod

version: 0.5.1

commands:
    menu:
        description: Player specific menu response commands
        usage: /menu
    qm:
        description: Quick launch config specified menus
        usage: /qm [Menu.command from config file]