name: MenuMetaMod

main: com.shawlyne.mc.MenuMetaMod.MenuMetaMod

version: 0.8

commands:
    qm:
        description: Quick launch config specified menus
        usage: /qm [Menu.command from config file]